### ISSUE TITLE
Form support in R Interpreter

### ISSUE THREAD

**Issue by samuel-pt** [datalayer/zeppelin-R#1]
Thanks a lot for providing R Interpreter.
I've integrated into my zeppelin and its working fine.

When I tried to use form or ${}, the form is not displayed in notebook as well the values are not substituted.
For example, I tried the below R script

```
%r
z <- seq(-3,form.input("val1", 3),${val2=.1})
d <- dnorm(z)
plot(z,d,type="l")
```
And below is the error 
> voidEval failed, request status: error code: 127

I tried with just form as well like below
```
%r
z <- seq(-3,form.input("val1", 3),form.input("val2", .1))
d <- dnorm(z)
plot(z,d,type="l")
```
Got the below error
> Error in seq.default(-3, form.input("val1", 3), form.input("val2", 0.1)): could not find function "form.input"

Is the form supported in R interpreter?

**Comment by echarles** [comment]
Hi Samuel, Sorry for the late answer... busy time yeah...
Good to read you can use our R Interpreter. In short, form is not supported.
Are you referring to the R form (which I never used by the way), or to the zeppelin forms (in which case it is certainly not supported today, although it would be IMHO technically possible) ?

**Comment by samuel-pt** [comment]
Thanks Eric,

That's fine no problems. 
I was referring zeppelin forms. If there is a strong requirement for me, I will try to code for supporting zeppelin forms
