### ISSUE TITLE
zeppelin-R build fails with bower 

### ISSUE THREAD

**Issue by samuel-pt** [datalayer/zeppelin-R#3]
I am using the old version of zeppelin-R, which just gives you a interpreter jar which can be used to create an interpreter with minimal manual steps.

As we need to take data back and forth from R interpreter to scala interpreter, we would like to use new version of zeppelin-R. So I cloned this new version and provided the below command to build.
```
mvn clean install -Pspark-1.5 -Dspark.version=1.5.0 \
  -Dhadoop.version=2.7.1 -Phadoop-2.6 -Ppyspark \
  -Dmaven.findbugs.enable=false -Drat.skip=true -Dcheckstyle.skip=true \
  -DskipTests \
  -pl '!flink,!ignite,!phoenix,!postgresql,!tajo,!hive,!cassandra,!lens,!kylin'
```

Unfortunately I am getting the below exception

```
[INFO] Running 'bower --allow-root install' in /home/ubuntu/work/predictive-service/latest-zeppelin-R/zeppelin-R/zeppelin-web
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module '/home/ubuntu/work/predictive-service/latest-zeppelin-R/zeppelin-R/zeppelin-web/node_modules/bower/bin/bower'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR]     at startup (node.js:119:16)
[ERROR]     at node.js:901:3
[INFO] ------------------------------------------------------------------------
```

I tried with sudo as well. I am trying to build it on a EC2 instance.

Please help me to resolve this issue.

**Comment by echarles** [comment]
Zeppelin trunk had the same error and it has been fixed. I will merge trunk and push asap.

**Comment by echarles** [comment]
This comes from https://issues.apache.org/jira/browse/ZEPPELIN-634 which has just been fixed.
I have rebased. Can you pull rscala branch latest changes and try again?

**Comment by samuel-pt** [comment]
Thanks, now build is successful, but unfortunately not able to open notebooks.
The header of zeppelin UI and notebook UI is not rendering in notebook

Here is the screen shot
![zeppelin-r-2](https://cloud.githubusercontent.com/assets/13430878/12674191/95f2f824-c6a7-11e5-9019-6988e7a68897.png)

**Comment by echarles** [comment]
I double check (fresh build of latest commit) and it works well for me. Can you force refresh the page in your browser (Shift-F5)? next step would be to debug the http requests with firebug or chrome developer...

**Comment by samuel-pt** [comment]
I debugged the http requests using firebug. 
Zeppelin server returning HTTP status 500 for the request http://host:8080/api/security/ticket.

Do I need to set anything in cookie or do I need to add any property?
Sorry if I am not aware of that

**Comment by echarles** [comment]
I have a 200 (OK) on that HTTP request with response: {"status":"OK","message":"","body":{"principal":"anonymous","ticket":"anonymous"}}

This comes from the recent merge of the authentication based on Shiro which is configured by the ./conf/shiro.ini file. You should have that content for the [url] section:

```
[urls]
# anon means the access is anonymous.
# authcBasic means Basic Auth Security
# To enfore security, comment the line below and uncomment the next one
/** = anon
#/** = authcBasic
```

**Comment by samuel-pt** [comment]
With rebuild everything is working fine

Thanks a lot for your help
