### ISSUE TITLE
Executing R code taking too much time

### ISSUE THREAD

**Issue by samuel-pt** [datalayer/zeppelin-R#4]
I just built Zeppelin-R from github, set the SPARK_HOME in zeppelin-env.sh and started zeppelin.
When I execute R tutorial, the paragraphs which uses R interpreter takes too long and exited. 

When I try a simple scala code i.e. sc.version, I am getting the output in definite time.

Do I miss anything? Here is the screen shot
![zeppelin-r](https://cloud.githubusercontent.com/assets/13430878/12640079/1469fc64-c5ce-11e5-8d77-a45097a0bf53.png)

**Comment by echarles** [comment]
Are you building the rscala branch? I had such weird behavior having scala 2.10 in my classpath (the code expects to have scala 2.11). Is there any exception in the log file?

**Comment by samuel-pt** [comment]
Yes I've built rscala branch and  having scala 2.11 in my path. Log file does not show any errors.
I think we can delay this issue until https://github.com/datalayer/zeppelin-R/issues/4 resolved. Currently I got stuck with https://github.com/datalayer/zeppelin-R/issues/4

**Comment by samuel-pt** [comment]
With rebuild everything is working fine

Thanks a lot for your help
